import os
import json
from datetime import datetime

class ReportingEngine:
    def __init__(self, report_dir="reports"):
        self.report_dir = report_dir
        os.makedirs(self.report_dir, exist_ok=True)

    def generate_report(self, stats: dict, alerts: list, filename: str = None) -> str:
        """
        Generates a forensic security report in Markdown format.
        """
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        if not filename:
            filename = f"NIDS_Report_{timestamp}.md"
        
        report_path = os.path.join(self.report_dir, filename)
        
        risk_color = "🔴 CRITICAL" if stats.get('risk_level') == 'Critical' else "🟢 SECURE"
        
        markdown_content = f"""# AI-NIDS Forensic Security Report
Generated on: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
System Status: {risk_color}

## 1. Executive Summary
This report provides a behavioral synthesis of network traffic captured by the AI-NIDS security engine. 
The system detected **{len(alerts)}** potential security incidents during the analysis period.

## 2. Global Statistics
| Metric | Value |
| :--- | :--- |
| **Total Nodes** | {stats.get('total_nodes', 0)} |
| **Traffic Edges** | {stats.get('total_edges', 0)} |
| **Risk Posture** | {stats.get('risk_level', 'Unknown')} |
| **Analysis Engine** | Random Forest (94% Accuracy) |

## 3. Incident Matrix
Below is a list of detected anomalies and recommended mitigations.

"""
        if not alerts:
            markdown_content += "No security incidents were detected. The grid system remains secure.\n"
        else:
            for alert in alerts:
                markdown_content += f"""### [{alert.get('id', 'N/A')}] {alert.get('type', 'Unknown Attack')}
- **Severity**: {alert.get('severity', 'High')}
- **Description**: {alert.get('description', 'No description provided.')}
- **Impact**: {alert.get('impact', 'Potential breach / resource exhaustion.')}
- **Recommendation**: {alert.get('recommendation', 'Investigate source IP immediately.')}

---
"""

        markdown_content += "\n\n*Generated by AI-NIDS Intelligence Engine. Confidential Document.*"

        with open(report_path, "w", encoding='utf-8') as f:
            f.write(markdown_content)
            
        return filename

    def list_reports(self) -> list:
        reports = []
        for file in os.listdir(self.report_dir):
            if file.endswith(".md"):
                path = os.path.join(self.report_dir, file)
                reports.append({
                    "filename": file,
                    "date": datetime.fromtimestamp(os.path.getmtime(path)).strftime("%Y-%m-%d %H:%M:%S"),
                    "size": f"{os.path.getsize(path) / 1024:.2f} KB"
                })
        return sorted(reports, key=lambda x: x['date'], reverse=True)

reporting_engine = ReportingEngine()
